### ISSUE TITLE
Temporal CLI based ephemeral server

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-dotnet#22] opened 2023-02-12 23:25 UTC
- [ ] Opt out of version check for servers started by the SDK test framework - there's no value for users since we typically start it without the UI and can't show upgrade notifications

**Comment by bergundy** [comment] 2023-02-12 23:26
Depends on https://github.com/temporalio/sdk-core/issues/485

No need to maintain support for Temporalite.

**Comment by cretz** [comment] 2023-05-25 19:24
Closing as duplicate of #50

**Closed as not planned by cretz** 2023-05-25 19:24 UTC
